### PR TITLE
Russian language

### PR DESCRIPTION
**Pull request by ijustbsd**

### CODE REVIEW

**Comment by vbonvin** [comment]
Looks to me that this PR is mostly about translating the current branch in Russian. Before merging, could you explain a bit more your work here, i.e:

- Is there a variable to tweak somewhere to switch between English and Russian languages ?
- With this code, will it be easy to add other languages in the future ?

**Comment by nickkolok** [comment]
@vbonvin, adding other languages will be a bit tricky, but in any case easier and more straight than direct translating like https://github.com/vbonvin/ipt_connect/commit/80362d215175b387e5be1ffe27d129df11036970

**Comment by nickkolok** [comment]
Question about switching the language remains addressed to @ijustbsd

**Comment by ijustbsd** [comment]
@vbonvin, you can switch language by changing `LANGUAGE_CODE` in the `settings.py` file. For example like [here](https://github.com/vbonvin/ipt_connect/pull/59/commits/84864bc980b373a8818b9d8f0c4e7082865aefb9). I'll add this to the README a bit later.

**Comment by vbonvin** [comment]
Ok, thanks for the reply. Sounds good to me, I'll merge.

**Pull request merged**
